name = "iNaturalistAPP"
uuid = "d79a016a-93e6-430d-8786-b3c21400f00e"
version = "0.1.0"

[deps]
Arrow = "69666777-d1a9-59fb-9406-91d4454c9d45"
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
Clustering = "aaaa29a8-35af-508c-8bc3-b662a17a0fe5"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
Genie = "c43c736e-a2d1-11e8-161f-af95117fbd1e"
HTTP = "cd3eb016-35fb-5094-929b-558a96fad6f3"
JSON3 = "0f8b85d8-7281-11e9-16c2-39a750bddbf1"
Parsers = "69de0a69-1ddd-5017-9359-2bf0b02dc9f0"
PlotlyJS = "f0f68f2c-4968-5e81-91da-67840de0976a"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
Logging = "56ddb016-857b-54e1-b83d-db4d58db5568"
